[package]
name = "run_solution"
version = "0.1.0"
edition = "2021"

[dependencies]
utils = { path = "../utils" }
dayXX = { path = "../dayXX" }
day01 = { path = "../day01" }
day02 = { path = "../day02" }
day03 = { path = "../day03" }
day04 = { path = "../day04" }
